name: Our Workflow
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: vote-project  # 🔹 실행 폴더를 지정
