name: Our Workflow
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
        - run: npm ci
          working-directory: vote-project  # 🔹 실행 폴더를 지정
