name: Our Jobs
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ githun.job }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ githun.job }}
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ githun.job }}
