name: Our Jobs
on: push
jobs:
  date1:
    runs-on: ubuntu-latest
    steps:
      - run : echo 'Hello!'
  date2:
    runs-on: window-latest
    steps:
      - run: echo 'Hello, Main'
  date3:
    runs-on: macos-latest
    steps:
      - run: date
