name: Our Push
on:
  push:
jobs:
  echo:
    runs-on: unbuntu-latest
    steps:
      - run: echo "ref_name=${{ github.ref_name }}"
      - run: echo "sha=${{ github.sha }}"
      - run: echo echo "name=${{ github.event_name }}"
      
