name: Our release
on:
  release:
    types: [published]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "name=${{ github.event.name }}"
      - run: echo "action=${{ github.event.action }}"
      - run: echo "ref_name=${{ github.ref_name }}"
      
